
export const menudata = [
    {
        title: "All",
        imgUrl: "/assets/hero/dcfood-hero.webp",
        subItem: [
            {
                id: 1,
                type: "beef",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Premium Basmati Rice",
                subtitle: "Served with mashed potatoes",
                amount: 1,
                price: 35000,
            },
            {
                id: 2,
                type: "flour",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Semovita Premium",
                subtitle: "Original made in Nigeria semo",
                price: 56700,
                amount: 1,
            },
            {
                id: 3,
                type: "veggie",
                image: "/assets/products/tropical-basmatic-rice.webp",
                subtitle: "Fresh greens and colorful vegetables",
                title: "Healthy Veggie Salad",
                price: 34500,
                amount: 1,
            },
            {
                id: 4,
                type: "beef",
                image: "/assets/products/tropical-basmatic-rice.webp",
                subtitle: "Served with mashed potatoes",
                title: "Healthy Veggie Salad",
                price: 9.99,
                amount: 1,
            },


        ]
    },
    {
        title: "Beverages",
        imgUrl: "/assets/category/beverages.webp",
        subItem: [
            {
                id: 8,
                weight: 250,
                type: "beef",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 9,
                weight: 200,
                type: "veggie",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 10,
                weight: 250,
                type: "beef",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 11,
                weight: 200,
                type: "veggie",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 12,
                weight: 250,
                type: "beef",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 13,
                weight: 200,
                type: "veggie",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },


        ]
    },
    {
        title: "Canned Food",
        imgUrl: "/assets/category/canned_food.webp",
        subItem: [
            {
                id: 14,
                weight: 250,
                type: "beef",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 15,
                weight: 200,
                type: "veggie",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 16,
                weight: 250,
                type: "beef",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 17,
                weight: 200,
                type: "veggie",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 18,
                weight: 200,
                type: "veggie",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 19,
                weight: 250,
                type: "beef",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 20,
                weight: 200,
                type: "veggie",
                image: "/assets/products/tropical-basmatic-rice.webp",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
        ]
    },
    {
        title: "Cooking Oil",
        imgUrl: "/assets/category/cooking_oil.webp",
        subItem: [
            {
                id: 21,
                weight: 250,
                type: "beef",
                image: "https://img.freepik.com/free-photo/double-hamburger-isolated-white-background-fresh-burger-fast-food-with-beef-cream-cheese_90220-1192.jpg?w=2000",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 22,
                weight: 200,
                type: "veggie",
                image: "https://img.freepik.com/free-photo/double-hamburger-isolated-white-background-fresh-burger-fast-food-with-beef-cream-cheese_90220-1192.jpg?w=2000",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 23,
                weight: 250,
                type: "beef",
                image: "https://img.freepik.com/free-photo/double-hamburger-isolated-white-background-fresh-burger-fast-food-with-beef-cream-cheese_90220-1192.jpg?w=2000",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 24,
                weight: 200,
                type: "veggie",
                image: "https://img.freepik.com/free-photo/double-hamburger-isolated-white-background-fresh-burger-fast-food-with-beef-cream-cheese_90220-1192.jpg?w=2000",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
        ]
    },
    {
        title: "Flour",
        imgUrl: "/assets/category/flour.webp",

        subItem: [
            {
                id: 25,
                weight: 250,
                type: "beef",
                image: "https://www.nospoonnecessary.com/wp-content/uploads/2014/09/Tortillas-Recipe.jpg",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 26,
                weight: 200,
                type: "veggie",
                image: "https://www.nospoonnecessary.com/wp-content/uploads/2014/09/Tortillas-Recipe.jpg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 27,
                weight: 250,
                type: "beef",
                image: "https://www.nospoonnecessary.com/wp-content/uploads/2014/09/Tortillas-Recipe.jpg",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 28,
                weight: 200,
                type: "veggie",
                image: "https://www.nospoonnecessary.com/wp-content/uploads/2014/09/Tortillas-Recipe.jpg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 29,
                weight: 200,
                type: "veggie",
                image: "https://www.nospoonnecessary.com/wp-content/uploads/2014/09/Tortillas-Recipe.jpg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
        ]
    },
    {
        title: "Grains",
        imgUrl: "/assets/category/grains.webp",

        subItem: [
            {
                id: 30,
                weight: 250,
                type: "beef",
                image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/1200px-Korb_mit_Br%C3%B6tchen.JPG",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 31,
                weight: 200,
                type: "veggie",
                image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/1200px-Korb_mit_Br%C3%B6tchen.JPG",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 32,
                weight: 250,
                type: "beef",
                image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/1200px-Korb_mit_Br%C3%B6tchen.JPG",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 33,
                weight: 200,
                type: "veggie",
                image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/1200px-Korb_mit_Br%C3%B6tchen.JPG",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 34,
                weight: 250,
                type: "beef",
                image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/1200px-Korb_mit_Br%C3%B6tchen.JPG",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 35,
                weight: 200,
                type: "veggie",
                image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/1200px-Korb_mit_Br%C3%B6tchen.JPG",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
        ]
    },
    {
        title: "Legumes",
        imgUrl: "/assets/category/legumes.webp",

        subItem: [
            {
                id: 36,
                weight: 250,
                type: "beef",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 37,
                weight: 200,
                type: "veggie",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 38,
                weight: 250,
                type: "beef",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 39,
                weight: 200,
                type: "veggie",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
        ]
    },
    {
        title: "Pasta & Noodles",
        imgUrl: "/assets/category/pasta.webp",
        subItem: [
            {
                id: 40,
                weight: 250,
                type: "beef",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 41,
                weight: 200,
                type: "veggie",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 42,
                weight: 250,
                type: "beef",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 43,
                weight: 200,
                type: "veggie",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
        ]
    },
    {
        title: "Seasoning",
        imgUrl: "/assets/category/seasoning.webp",

        subItem: [
            {
                id: 44,
                weight: 250,
                type: "beef",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 45,
                weight: 200,
                type: "veggie",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
            {
                id: 46,
                weight: 250,
                type: "beef",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Delicious Beef Dish",
                subtitle: "Served with mashed potatoes",
                price: 12.99,
            },
            {
                id: 47,
                weight: 200,
                type: "veggie",
                image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/2/4/1/RX-FNM_030111-Weeknight-Dinners-025_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539864691.jpeg",
                title: "Healthy Veggie Salad",
                subtitle: "Fresh greens and colorful vegetables",
                price: 9.99,
            },
        ]
    },
];