const endpoints = {
	getTestimonials: "api/testimonial",
	getBlogs: "api/blog",
	getBlogById: (id) => `api/blog/${id}`,
	getBlogCommentsById: (id) => `api/blog/${id}/blogcomment`,
	getBlogComments: "api/blog/blogcomment/",
	contactUs: "api/contact_us",
	getOrderById: (id) => `api/order/${id}/payment`,
	getOrdersCallback: (id) => `api/orders/${id}/payment/callback`,
	getPaymentSummary: (id) => `api/orders/${id}/payment/summary`,
	getBestCombo: "api/products/products_combo/",
	getPaymentCallback: "api/payment/{id}/callback",
	getProducts: "api/products/",
	getProductByCategories: "api/products/categories/",
	postTags:"api/products/tags/",
	getProductByCategoriesId: (id) => `api/products/categories/${id}/`,
	getProductCoupon: (id) => `api/products/coupon/${id}/apply`,
	getProductsById: (id) => `api/products/${id}`,
	getFavoriteProducts: "api/products/favourite_product",
	getFavoriteProductsById: (id) => `api/products/favorite_product/${id}`,
	getDeliveryArea: "api/delivery/delivery-area/",
	getDeliveryAxisById: (id) => `api/delivery/delivery-axis/${id}`,
	login: "auth/login",
	forgotPassword: "auth/forgot-password",
	changePassword: "auth/change-password",
	confirmPasswordReset: "auth/confirm-password-reset",
	getActivationToken: (uid) => `auth/activation/${uid}/token`,
	user: "auth/me",
	register: "auth/register",
	verify: "auth/verify",
	resendActivation: "auth/resend-activation",
	registerAdmin: "auth/register-admin",
	refresh: "auth/refresh",
	users: "api/customers",
	staffs: "api/staff",
	orders: "api/orders/admin",
};

export default endpoints;
