export const mockTableData = [
	{
		id: 1,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 2,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 3,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 4,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 5,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 6,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 7,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 8,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 9,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 10,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 11,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
	{
		id: 12,
		customer_name: "Bright Iortsor",
		delivery_address: "No 1, Bright Street, Lagos",
		phone_number: "08012345678",
		email: "johndoe@gmail.com",
	},
];
