const products = [
    // Grains
    {
        id: 1,
        category: "Grains",
        name: "Rice",
        description: "Premium long-grain rice for everyday meals",
        weight: "5kg",
        price: 3000,
        image: "rice.webp",
    },
    {
        id: 2,
        category: "Grains",
        name: "Cornmeal",
        description: "Finely ground cornmeal for baking and cooking",
        weight: "2kg",
        price: 1200,
        image: "cornmeal.webp",
    },
    {
        id: 3,
        category: "Grains",
        name: "Quinoa",
        description: "Organic quinoa grains for a nutritious meal",
        weight: "1kg",
        price: 2500,
        image: "quinoa.webp",
    },
    {
        id: 4,
        category: "Grains",
        name: "Oats",
        description: "Rolled oats for a healthy breakfast",
        weight: "1.5kg",
        price: 900,
        image: "oats.webp",
    },
    {
        id: 5,
        category: "Grains",
        name: "Barley",
        description: "Whole grain barley for soups and stews",
        weight: "500g",
        price: 800,
        image: "barley.webp",
    },

    // Flour
    {
        id: 6,
        category: "Flour",
        name: "Wheat Flour",
        description: "High-quality wheat flour for baking purposes",
        weight: "2kg",
        price: 1200,
        image: "wheat_flour.webp",
    },
    {
        id: 7,
        category: "Flour",
        name: "All-Purpose Flour",
        description: "Versatile all-purpose flour for various recipes",
        weight: "1kg",
        price: 600,
        image: "all_purpose_flour.webp",
    },
    {
        id: 8,
        category: "Flour",
        name: "Corn Flour",
        description: "Finely ground corn flour for baking and thickening",
        weight: "500g",
        price: 500,
        image: "corn_flour.webp",
    },
    {
        id: 9,
        category: "Flour",
        name: "Coconut Flour",
        description: "Gluten-free coconut flour for baking",
        weight: "500g",
        price: 1500,
        image: "coconut_flour.webp",
    },
    {
        id: 10,
        category: "Flour",
        name: "Rice Flour",
        description: "Stone-ground rice flour for gluten-free recipes",
        weight: "1kg",
        price: 900,
        image: "rice_flour.webp",
    },

    // Cooking Oil
    {
        id: 11,
        category: "Cooking Oil",
        name: "Vegetable Oil",
        description: "Refined vegetable oil for cooking and frying",
        weight: "3L",
        price: 2500,
        image: "vegetable_oil.webp",
    },
    {
        id: 12,
        category: "Cooking Oil",
        name: "Olive Oil",
        description: "Extra virgin olive oil for healthy cooking",
        weight: "750ml",
        price: 4000,
        image: "olive_oil.webp",
    },
    {
        id: 13,
        category: "Cooking Oil",
        name: "Sunflower Oil",
        description: "Pure sunflower oil for everyday cooking",
        weight: "2L",
        price: 2000,
        image: "sunflower_oil.webp",
    },
    {
        id: 14,
        category: "Cooking Oil",
        name: "Coconut Oil",
        description: "Organic virgin coconut oil for cooking and beauty",
        weight: "500ml",
        price: 3000,
        image: "coconut_oil.webp",
    },
    {
        id: 15,
        category: "Cooking Oil",
        name: "Palm Oil",
        description: "Pure palm oil for traditional African cuisine",
        weight: "1L",
        price: 1500,
        image: "palm_oil.webp",
    },

    // Pasta & Noodles
    {
        id: 16,
        category: "Pasta & Noodles",
        name: "Spaghetti",
        description: "Long, thin pasta strands made from durum wheat",
        weight: "1kg",
        price: 600,
        image: "spaghetti.webp",
    },
    {
        id: 17,
        category: "Pasta & Noodles",
        name: "Macaroni",
        description: "Curved pasta tubes for a variety of dishes",
        weight: "500g",
        price: 500,
        image: "macaroni.webp",
    },
    {
        id: 18,
        category: "Pasta & Noodles",
        name: "Fusilli",
        description: "Spiral-shaped pasta for salads and casseroles",
        weight: "750g",
        price: 700,
        image: "fusilli.webp",
    },
    {
        id: 19,
        category: "Pasta & Noodles",
        name: "Ramen Noodles",
        description: "Instant noodles with various flavor options",
        weight: "100g",
        price: 200,
        image: "ramen_noodles.webp",
    },
    {
        id: 20,
        category: "Pasta & Noodles",
        name: "Udon Noodles",
        description: "Thick wheat noodles for soups and stir-fries",
        weight: "200g",
        price: 400,
        image: "udon_noodles.webp",
    },

    // Canned Food
    {
        id: 21,
        category: "Canned Food",
        name: "Canned Sardines",
        description: "Sardines packed in tomato sauce for a quick meal",
        weight: "425g",
        price: 700,
        image: "sardines.webp",
    },
    {
        id: 22,
        category: "Canned Food",
        name: "Canned Tuna",
        description: "Flaked tuna in oil or brine for sandwiches and salads",
        weight: "185g",
        price: 900,
        image: "canned_tuna.webp",
    },
    {
        id: 23,
        category: "Canned Food",
        name: "Canned Sweet Corn",
        description: "Golden sweet corn kernels for various recipes",
        weight: "340g",
        price: 400,
        image: "sweet_corn.webp",
    },
    {
        id: 24,
        category: "Canned Food",
        name: "Canned Baked Beans",
        description: "Classic baked beans in tomato sauce",
        weight: "415g",
        price: 600,
        image: "baked_beans.webp",
    },
    {
        id: 25,
        category: "Canned Food",
        name: "Canned Chickpeas",
        description: "Tender chickpeas for salads and hummus",
        weight: "400g",
        price: 500,
        image: "chickpeas.webp",
    },

    // Beverages
    {
        id: 26,
        category: "Beverages",
        name: "Tea Bags",
        description: "Premium tea bags for a refreshing hot beverage",
        weight: "100 tea bags",
        price: 900,
        image: "tea_bags.webp",
    },
    {
        id: 27,
        category: "Beverages",
        name: "Instant Coffee",
        description: "Premium instant coffee granules for a quick brew",
        weight: "200g",
        price: 1500,
        image: "instant_coffee.webp",
    },
    {
        id: 28,
        category: "Beverages",
        name: "Hot Chocolate",
        description: "Rich and creamy hot chocolate powder",
        weight: "500g",
        price: 1200,
        image: "hot_chocolate.webp",
    },
    {
        id: 29,
        category: "Beverages",
        name: "Fruit Juice",
        description: "Assorted fruit juice blend with no added sugar",
        weight: "1L",
        price: 800,
        image: "fruit_juice.webp",
    },
    {
        id: 30,
        category: "Beverages",
        name: "Sports Drink",
        description: "Replenishing sports drink for hydration",
        weight: "500ml",
        price: 500,
        image: "sports_drink.webp",
    },

    // Beans & Legumes
    {
        id: 31,
        category: "Beans & Legumes",
        name: "Black Beans",
        description: "Dried black beans for nutritious meals",
        weight: "500g",
        price: 800,
        image: "black_beans.webp",
    },
    {
        id: 32,
        category: "Beans & Legumes",
        name: "Kidney Beans",
        description: "Red kidney beans for stews and salads",
        weight: "1kg",
        price: 1000,
        image: "kidney_beans.webp",
    },
    {
        id: 33,
        category: "Beans & Legumes",
        name: "Chickpeas",
        description: "Versatile chickpeas for salads and curries",
        weight: "500g",
        price: 700,
        image: "chickpeas.webp",
    },
    {
        id: 34,
        category: "Beans & Legumes",
        name: "Lentils",
        description: "Protein-rich lentils for soups and stews",
        weight: "1kg",
        price: 900,
        image: "lentils.webp",
    },
    {
        id: 35,
        category: "Beans & Legumes",
        name: "Soybeans",
        description: "Whole soybeans for tofu and soy-based dishes",
        weight: "1kg",
        price: 1200,
        image: "soybeans.webp",
    },
];

export default products;
